// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import PublicNav from './navigation/PublicNav'; // Adjust import path as needed
import './globals.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </head>
      <body className={inter.className}>
        <div className="layout-wrapper">
          <main className="main-content">{children}</main>
        </div>
      </body>
    </html>
  );
}
